import numpy as np
from utils.tf_utils import get_early_stop

param_dict_bak = {"mode": "dev",
                  "model_dir": "./model_dir",
                  "data_dir": "../../data/movieLens1m_201809",
                  "data_file": "data.csv",
                  "train_file": "train.csv",
                  "test_file": "test.csv",
                  "all_columns": ["userId", "movieId", "label", "rating", "screen_year", "rating_counts",
                                  "rating_mean", "genres", "click_seq"],
                  "cat_columns": ["screen_year", "rating_counts", "rating_mean"],
                  "seq_columns": {"genres": 10, "click_seq": 30},
                  "data_type": [np.str, np.str, np.float, np.float, np.str, np.str, np.str, np.str, np.str],
                  "default_val": [[""]] * 2 + [[0.0]] * 2 + [[""]] * 5,
                  "delimiter": ",",
                  "padding_value": "padding_value",
                  "min_hit": 3,
                  "emb_size": 128,
                  "act_fun": "relu",
                  "reg_fun": "l2",
                  "batch_size": 128,
                  "learning_rate": 0.001,
                  "optimizer": "adam",
                  "loss_fun": "binary_cross_entropy",
                  "from_logits": False,
                  "metrics": ["auc"],
                  "callbacks": None,
                  "epoch_num": 1}

params = {
    "mode": "train",
    "train_file": "D:\\git\\recommendation\\data\\ml-25m\\ml-25m\\train.csv",
    "test_file": "D:\\git\\recommendation\\data\\ml-25m\\ml-25m\\test.csv",
    "factor_dim": 50,
    "batch_size": 1024,
    "optimizer": "adam",
    "learning_rate": 0.001,
    "loss_function": "binary_cross_entropy",
    "from_logits": False,
    "metrics": ["auc"],
    "callbacks": None,
    "epoch_num": 1,
    "min_hits": 300,
    "model_dir": "D:\\git\\recommendation\\models\\fm\\model_dir",
    "all_columns": {"userId": str, "movieId": str, "rating": float, "timestamp": int,
                    "title": str, "genres": str, "tag": str, "publish_year": str, "click_seq": str,
                    "user_rating_movies": str, "user_average_rating": str, "user_most_rated_genre": str,
                    "user_favourite_genre": str, "label": float},
    "cat_columns": ["tag", "publish_year", "user_rating_movies", "user_average_rating", "user_most_rated_genre",
                    "user_favourite_genre"],
    "seq_columns": {"genres": 5, "click_seq": 30},
    "field_delimiter": ",",
    "seq_delimiter": "|",
    "padding_value": "padding_value",
}
