# DATASET
MOVIELENS_25M_MOVIES = "E:/movielens/ml-25m/ml-25m/movies.csv"
MOVIELENS_25M_RATINGS = "E:/movielens/ml-25m/ml-25m/ratings.csv"
MOVIELENS_25M_TAGS = "E:/movielens/ml-25m/ml-25m/tags.csv"

# INSTANCE
MOVIELENS_POSITIVE_THRESHOLD = 4
MOVIELENS_MAX_CLICK_LENGTH = 30
MOVIELENS_TRAIN_TEST_SPLIT_DATE = "2017-01-01"
MOVIELENS_TRAIN_DATA_PATH = "E:/movielens/ml-25m/ml-25m/train.csv"
MOVIELENS_TEST_DATA_PATH = "E:/movielens/ml-25m/ml-25m/test.csv"

# FEATURES
MOVIELENS_SPARSE_FEATURES = [""]